import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPortfolioDetail } from '@/lib/server/deal-lifecycle';
import { holdingDays, saleEconomics } from '@/lib/deal-lifecycle';
import { createOffer, recordRenewalDecision, recordSale, updateHolding, updateOfferStatus } from './actions';

export const dynamic = 'force-dynamic';
const currency = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const date = (value: Date) => value.toISOString().slice(0, 10);
const field = 'rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm';

export default async function PortfolioDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const holding = await getPortfolioDetail(id);
  if (!holding) notFound();
  const realizedProfit = holding.sales.reduce((sum, sale) => sum + sale.netProfit, 0);
  const fields: Array<[string, string, string | number, 'text' | 'number']> = [
    ['Registrar', 'registrar', holding.registrar, 'text'], ['Purchase source', 'purchaseSource', holding.purchaseSource ?? '', 'text'],
    ['Purchase cost', 'purchaseCost', holding.purchaseCost, 'number'], ['Renewal cost', 'renewalCost', holding.renewalCost, 'number'],
    ['Current valuation', 'currentValuation', holding.currentValuation, 'number'], ['Buy-now price', 'buyNowPrice', holding.buyNowPrice ?? 0, 'number'],
    ['Minimum sale price', 'minSalePrice', holding.minSalePrice ?? 0, 'number'], ['Category', 'category', holding.category ?? '', 'text'],
  ];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Link className="text-sm text-brand" href="/portfolio">Portfolio</Link><h1 className="mt-2 text-3xl font-bold">{holding.domain.name}</h1><p className="mt-2 text-sm text-slate-400">Acquisition, valuation, offers, sales, renewals, and activity.</p></div><Link className="rounded-lg border border-white/10 px-4 py-2 text-sm" href="/renewals">Renewal calendar</Link></div>
    <div className="mt-6 grid gap-4 md:grid-cols-4">{[['Cost', currency(holding.purchaseCost)], ['Valuation', currency(holding.currentValuation)], ['Open offers', String(holding.offers.filter((offer) => ['RECEIVED','COUNTERED'].includes(offer.status)).length)], ['Realized profit', currency(realizedProfit)]].map(([label,value]) => <div className="card" key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">
      <form action={updateHolding} className="card grid gap-3 sm:grid-cols-2"><input name="id" type="hidden" value={id}/><h2 className="text-xl font-semibold sm:col-span-2">Holding details</h2>
        {fields.map(([label,name,value,type]) => <label className="grid gap-1 text-sm" key={name}><span className="text-slate-400">{label}</span><input className={field} name={name} defaultValue={value} type={type} step={type === 'number' ? '0.01' : undefined}/></label>)}
        <label className="grid gap-1 text-sm"><span className="text-slate-400">Expiration</span><input className={field} name="expirationDate" defaultValue={date(holding.expirationDate)} type="date"/></label><label className="flex items-center gap-2 pt-6 text-sm"><input defaultChecked={holding.autoRenew} name="autoRenew" type="checkbox"/> Auto-renew</label>
        <label className="grid gap-1 text-sm sm:col-span-2"><span className="text-slate-400">Tags</span><input className={field} name="tags" defaultValue={holding.tags.join(', ')}/></label><label className="grid gap-1 text-sm sm:col-span-2"><span className="text-slate-400">Nameservers</span><input className={field} name="nameservers" defaultValue={holding.nameservers.join(', ')}/></label><label className="grid gap-1 text-sm sm:col-span-2"><span className="text-slate-400">Notes</span><textarea className={field} name="notes" defaultValue={holding.notes ?? ''}/></label><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold sm:col-span-2">Save holding</button>
      </form>
      <div className="grid gap-4"><form action={createOffer} className="card grid gap-3 sm:grid-cols-2"><input name="id" type="hidden" value={id}/><h2 className="text-xl font-semibold sm:col-span-2">New offer</h2><input className={field} name="amount" min="0" placeholder="Amount" required step="0.01" type="number"/><input className={field} name="buyerName" placeholder="Buyer name"/><input className={field} name="buyerEmail" placeholder="Buyer email" type="email"/><input className={field} name="notes" placeholder="Notes"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold sm:col-span-2">Record offer</button></form>
        <form action={recordSale} className="card grid gap-3 sm:grid-cols-2"><input name="id" type="hidden" value={id}/><h2 className="text-xl font-semibold sm:col-span-2">Complete sale</h2><input className={field} name="salePrice" min="0" placeholder="Sale price" required step="0.01" type="number"/><input className={field} name="fees" min="0" placeholder="Fees" required step="0.01" type="number"/><input className={field} defaultValue={date(new Date())} name="saleDate" required type="date"/><input className={field} name="source" placeholder="Marketplace/source"/><textarea className={`${field} sm:col-span-2`} name="notes" placeholder="Sale notes"/><button className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold sm:col-span-2">Record completed sale</button></form></div>
    </section>
    <section className="mt-6 grid gap-4 xl:grid-cols-2"><div className="card"><h2 className="text-xl font-semibold">Negotiation history</h2><div className="mt-4 grid gap-3">{holding.offers.length ? holding.offers.map((offer) => <div className="border-l-2 border-white/10 pl-3" key={offer.id}><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{currency(offer.amount)} · {offer.buyerName ?? 'Unidentified buyer'}</p><span className="text-xs text-slate-400">{offer.status}</span></div><p className="mt-1 text-sm text-slate-400">{offer.notes || offer.buyerEmail || 'No notes'}</p><form action={updateOfferStatus} className="mt-2 flex gap-2"><input name="id" type="hidden" value={id}/><input name="offerId" type="hidden" value={offer.id}/><select className={field} defaultValue={offer.status} name="status"><option>RECEIVED</option><option>COUNTERED</option><option>ACCEPTED</option><option>DECLINED</option><option>WITHDRAWN</option></select><button className="rounded-lg border border-white/10 px-3 text-xs">Update</button></form></div>) : <p className="text-sm text-slate-400">No offers recorded.</p>}</div></div>
      <div className="card"><h2 className="text-xl font-semibold">Renewal decision</h2><p className="mt-2 text-sm text-slate-400">Next renewal: {date(holding.expirationDate)} · {currency(holding.renewalCost)}</p><form action={recordRenewalDecision} className="mt-4 grid gap-3"><input name="id" type="hidden" value={id}/><select className={field} name="decision"><option value="KEEP">Keep</option><option value="REVIEW">Review later</option><option value="DROP">Drop</option></select><textarea className={field} name="notes" placeholder="Decision rationale"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold">Save decision</button></form>{holding.renewals.map((renewal) => <p className="mt-3 text-sm" key={renewal.id}>{renewal.decision ?? renewal.status} · {date(renewal.dueDate)} · {renewal.notes ?? renewal.recommendation}</p>)}</div></section>
    <section className="mt-6 grid gap-4 xl:grid-cols-2"><div className="card"><h2 className="text-xl font-semibold">Completed sales</h2>{holding.sales.map((sale) => { const economics=saleEconomics(sale.salePrice,sale.fees,holding.purchaseCost); return <div className="mt-3 border-l-2 border-emerald-500/40 pl-3" key={sale.id}><p className="font-semibold">{currency(sale.salePrice)} sale · {currency(economics.netProfit)} profit</p><p className="text-sm text-slate-400">{economics.roi.toFixed(1)}% ROI · {holdingDays(holding.purchaseDate,sale.saleDate)} days held · {currency(sale.fees)} fees</p></div>;})}{!holding.sales.length && <p className="mt-3 text-sm text-slate-400">No completed sales.</p>}</div><div className="card"><h2 className="text-xl font-semibold">Activity</h2>{holding.activity.map((event) => <div className="mt-3 border-l-2 border-white/10 pl-3" key={event.id}><p className="text-sm font-semibold">{event.action}</p><p className="text-xs text-slate-500">{event.createdAt.toLocaleString()}</p></div>)}</div></section>
  </div>;
}
