import { acceptPublicBusinessPolicy, createComparableSale, importComparableSales, removeComparableSale, reviewComparableSalesUpload, syncComparableSales, syncPublicBusinessEvidence } from './actions';
import { getResearchView } from '@/lib/server/research';

export const dynamic = 'force-dynamic';
const money = (value: { toString(): string }) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value));
const age = (value: Date) => `${Math.max(0, Math.floor((Date.now() - value.getTime()) / 3_600_000))}h old`;
const isStale = (value: unknown) => Boolean(value && typeof value === 'object' && !Array.isArray(value) && (value as { stale?: unknown }).stale === true);

export default async function ResearchPage({ searchParams }: { searchParams?: Promise<{ subject?: string; marketplace?: string; source?: string; batch?: string; imported?: string }> }) {
  const params = await searchParams ?? {}; const view = await getResearchView(params); const rows = Array.isArray(view.batch?.rows) ? view.batch.rows as Array<{ row: number; subjectDomain: string; domain: string; status: string; message: string }> : [];
  return <div>
    <div><h1 className="text-3xl font-bold">Research</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Workspace-owned comparable sales, provider synchronization, and approved public-business evidence.</p></div>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">
      <form action={createComparableSale} className="card grid gap-3"><h2 className="text-xl font-semibold">Record comparable sale</h2><div className="grid gap-3 sm:grid-cols-2"><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="subjectDomain" required><option value="">Subject domain</option>{view.domains.map((item) => <option key={item.name}>{item.name}</option>)}</select><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="domain" placeholder="Comparable domain" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" min="1" name="price" placeholder="Sale price" type="number" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="saleDate" type="date" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="marketplace" placeholder="Marketplace" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="industry" placeholder="Industry" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 sm:col-span-2" name="evidenceUrl" placeholder="HTTPS evidence URL" type="url" /></div><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold">Save sale</button></form>
      <div className="card"><h2 className="text-xl font-semibold">Provider synchronization</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><form action={syncComparableSales} className="grid gap-2"><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="subjectDomain" required><option value="">Subject domain</option>{view.domains.map((item) => <option key={item.name}>{item.name}</option>)}</select><button className="rounded-lg border border-white/10 px-3 py-2 text-sm font-semibold">Sync comparable sales</button></form><form action={syncPublicBusinessEvidence} className="grid gap-2"><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="subjectDomain" required><option value="">Subject domain</option>{view.domains.map((item) => <option key={item.name}>{item.name}</option>)}</select><button className="rounded-lg border border-white/10 px-3 py-2 text-sm font-semibold">Search public records</button></form></div><div className="mt-4 border-t border-white/10 pt-4 text-sm"><p className="text-slate-400">SEC EDGAR queries use public filing metadata and require identity verification before business use.</p>{view.consent ? <p className="mt-2 font-semibold text-emerald-300">Public-data policy accepted</p> : <form action={acceptPublicBusinessPolicy} className="mt-3"><button className="rounded-lg bg-brand px-3 py-2 font-semibold">Accept public-data policy</button></form>}</div></div>
    </section>
    <section className="card mt-6"><h2 className="text-xl font-semibold">Comparable-sales CSV</h2><p className="mt-1 text-sm text-slate-400">Columns: subject_domain, domain, price, sale_date, marketplace, industry, evidence_url.</p><form action={reviewComparableSalesUpload} className="mt-4 flex flex-col gap-3 sm:flex-row" encType="multipart/form-data"><input accept=".csv,text/csv" className="min-w-0 flex-1 rounded-lg border border-white/10 px-3 py-2" name="file" type="file" required /><button className="rounded-lg border border-white/10 px-4 py-2 font-semibold">Review CSV</button></form>{view.batch ? <div className="mt-4"><p className="text-sm">{view.batch.validRows} valid / {view.batch.duplicateRows} duplicates / {view.batch.errorRows} errors</p><div className="mt-3 max-h-64 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="text-slate-400"><th>Row</th><th>Subject</th><th>Comparable</th><th>Status</th><th>Message</th></tr></thead><tbody>{rows.map((row) => <tr className="border-t border-white/10" key={row.row}><td className="py-2">{row.row}</td><td>{row.subjectDomain}</td><td>{row.domain}</td><td>{row.status}</td><td>{row.message}</td></tr>)}</tbody></table></div>{view.batch.status === 'REVIEW' && view.batch.validRows ? <form action={importComparableSales} className="mt-3"><input name="id" type="hidden" value={view.batch.id} /><button className="rounded-lg bg-brand px-4 py-2 font-semibold">Import valid rows</button></form> : null}</div> : null}</section>
    <form action="/research" className="mt-6 grid gap-3 sm:grid-cols-[1fr_1fr_180px_auto]"><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={params.subject} name="subject" placeholder="Filter subject domain" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={params.marketplace} name="marketplace" placeholder="Filter marketplace" /><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={params.source ?? ''} name="source"><option value="">All sources</option><option>MANUAL</option><option>CSV</option><option>PROVIDER</option></select><button className="rounded-lg border border-white/10 px-4 py-2">Filter</button></form>
    <section className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-slate-400"><th className="pb-3">Subject</th><th>Comparable</th><th>Price</th><th>Marketplace</th><th>Source</th><th>Freshness</th><th></th></tr></thead><tbody>{view.sales.map((sale) => <tr className="border-t border-white/10" key={sale.id}><td className="py-3 pr-3">{sale.subjectDomain}</td><td className="pr-3">{sale.evidenceUrl ? <a className="text-brand" href={sale.evidenceUrl} rel="noreferrer" target="_blank">{sale.domain}</a> : sale.domain}</td><td className="pr-3">{money(sale.price)}</td><td className="pr-3">{sale.marketplace}</td><td className="pr-3">{sale.source}</td><td className={isStale(sale.metadata) ? 'pr-3 font-semibold text-amber-200' : 'pr-3'}>{age(sale.checkedAt)}{isStale(sale.metadata) ? ' / STALE' : ''}</td><td><form action={removeComparableSale}><input name="id" type="hidden" value={sale.id} /><button className="text-rose-300">Remove</button></form></td></tr>)}</tbody></table></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-2"><div><h2 className="text-xl font-semibold">Public-business evidence</h2><div className="mt-3 divide-y divide-white/10">{view.evidence.length ? view.evidence.map((item) => <div className="py-3" key={item.id}><a className="font-semibold text-brand" href={item.sourceUrl} rel="noreferrer" target="_blank">{item.companyName}</a><p className="mt-1 text-xs text-slate-400">{item.provider} / {item.jurisdiction ?? 'Unknown jurisdiction'} / {age(item.fetchedAt)}{item.stale ? ' / STALE' : ''}</p></div>) : <p className="text-sm text-slate-400">No public-business evidence saved.</p>}</div></div><div><h2 className="text-xl font-semibold">Provider usage today</h2><div className="mt-3 divide-y divide-white/10">{view.usage.length ? view.usage.map((item) => <div className="flex justify-between gap-3 py-3 text-sm" key={item.provider}><span>{item.provider}</span><span className="text-slate-400">{item.requestCount}/{view.config.providerPolicy.dailyQuota} requests / {item.cacheHits} cache hits / {item.failures} failures</span></div>) : <p className="text-sm text-slate-400">No provider requests recorded today.</p>}</div></div></section>
  </div>;
}
