import Link from 'next/link';
import { DISCOVERY_SOURCES, getDiscoveryView } from '@/lib/server/discovery';
import type { ImportReviewRow } from '@/lib/csv-mobility';
import { archiveSavedSearch, cancelDiscoveryJob, createSavedSearch, importReviewedCsv, reviewCsvUpload, runDiscovery, runSavedSearch } from './actions';

export const dynamic = 'force-dynamic';
const field = 'rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm';
const label = (value: string) => value.toLowerCase().replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase());

export default async function DiscoveryPage({ searchParams }: { searchParams?: Promise<{ batch?: string }> }) {
  const query = await searchParams; const view = await getDiscoveryView(query?.batch);
  const rows = Array.isArray(view.batch?.rows) ? view.batch.rows as unknown as ImportReviewRow[] : [];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Discovery operations</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Run source workflows, schedule searches, review CSV imports, and inspect durable job history.</p></div><div className="flex gap-2"><Link className="rounded-lg border border-white/10 px-4 py-2 text-sm" href="/api/exports/opportunities">Export opportunities</Link><Link className="rounded-lg border border-white/10 px-4 py-2 text-sm" href="/api/exports/portfolio">Export portfolio</Link></div></div>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">
      <form action={runDiscovery} className="card grid gap-3 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">Run discovery now</h2><select className={field} name="source">{DISCOVERY_SOURCES.map((source)=><option key={source}>{source}</option>)}</select><input className={field} name="query" placeholder="Search concept" required/><input className={field} name="industry" placeholder="Industry" defaultValue="general"/><input className={field} name="keywords" placeholder="Keywords, comma separated"/><input className={field} name="tlds" defaultValue=".com, .ai"/><input className={field} name="count" min="3" max="25" defaultValue="8" type="number"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold sm:col-span-2">Run source workflow</button></form>
      <form action={createSavedSearch} className="card grid gap-3 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">Save scheduled search</h2><input className={field} name="name" placeholder="Search name" required/><select className={field} name="schedule"><option>MANUAL</option><option>DAILY</option><option>WEEKLY</option></select><select className={field} name="source">{DISCOVERY_SOURCES.filter((source)=>source!=='MANUAL').map((source)=><option key={source}>{source}</option>)}</select><input className={field} name="query" placeholder="Search concept" required/><input className={field} name="industry" placeholder="Industry" defaultValue="general"/><input className={field} name="keywords" placeholder="Keywords"/><input className={field} name="tlds" defaultValue=".com"/><input className={field} name="count" min="3" max="25" defaultValue="8" type="number"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold sm:col-span-2">Save search</button></form>
    </section>
    <section className="card mt-6"><h2 className="text-xl font-semibold">CSV import review</h2><form action={reviewCsvUpload} className="mt-4 grid gap-3 sm:grid-cols-[1fr_220px_auto]" encType="multipart/form-data"><input className={field} name="file" accept=".csv,text/csv" required type="file"/><input className={field} name="industry" defaultValue="general"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold">Review file</button></form>
      {view.batch ? <div className="mt-5"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm"><strong>{view.batch.filename}</strong> · {view.batch.validRows} valid · {view.batch.duplicateRows} duplicates · {view.batch.errorRows} errors</p>{view.batch.status==='REVIEW'&&view.batch.validRows>0?<form action={importReviewedCsv}><input name="id" type="hidden" value={view.batch.id}/><button className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold">Import valid rows</button></form>:null}</div><div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th>Row</th><th>Domain</th><th>Status</th><th>Message</th></tr></thead><tbody>{rows.map((row,index)=><tr className="border-t border-white/10" key={`${row.row}-${index}`}><td className="py-2">{row.row}</td><td>{row.domain||'None'}</td><td>{row.status}</td><td>{row.message}</td></tr>)}</tbody></table></div></div>:null}
    </section>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">
      <div className="card"><h2 className="text-xl font-semibold">Saved searches</h2><div className="mt-4 grid gap-3">{view.searches.map((search)=><div className="border-l-2 border-white/10 pl-3" key={search.id}><div className="flex justify-between gap-3"><div><p className="font-semibold">{search.name}</p><p className="text-xs text-slate-400">{label(search.source)} · {search.schedule} · next {search.nextRunAt?.toLocaleString() ?? 'manual'}</p></div><div className="flex gap-2"><form action={runSavedSearch}><input name="id" type="hidden" value={search.id}/><button className="text-xs font-semibold text-brand">Run</button></form><form action={archiveSavedSearch}><input name="id" type="hidden" value={search.id}/><button className="text-xs text-slate-400">Archive</button></form></div></div></div>)}{!view.searches.length&&<p className="text-sm text-slate-400">No saved searches yet.</p>}</div></div>
      <div className="card"><h2 className="text-xl font-semibold">Job history</h2><div className="mt-4 grid gap-3">{view.jobs.map((job)=><div className="border-l-2 border-white/10 pl-3" key={job.id}><div className="flex justify-between gap-3"><div><p className="font-semibold">{label(job.source)} · {job.status}</p><p className="text-xs text-slate-400">{job.progress}% · {job.resultCount} results · {job.createdAt.toLocaleString()}</p>{job.error&&<p className="text-xs text-rose-300">{job.error}</p>}</div>{['QUEUED','RUNNING'].includes(job.status)?<form action={cancelDiscoveryJob}><input name="id" type="hidden" value={job.id}/><button className="text-xs text-rose-300">Cancel</button></form>:null}</div></div>)}{!view.jobs.length&&<p className="text-sm text-slate-400">No discovery runs yet.</p>}</div></div>
    </section>
  </div>;
}
