import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { parseDomainLines } from '@/lib/domain-parsing';
import { analyzeDomains, generateDomainIdeas, generationSchema, type DomainAnalysis, type GenerationInput } from '@/lib/domain-engine';
import { assertWorkspaceWriter, type WorkspaceContext } from './workspace-context';

export type PersistedOpportunity = {
  domainId: string;
  name: string;
  score: number;
  riskLevel: DomainAnalysis['riskLevel'];
  available: boolean;
};

function getTld(domain: string): string {
  const index = domain.lastIndexOf('.');
  return index >= 0 ? domain.slice(index) : '';
}

function normalizePersistedDomain(domain: string): string {
  return domain.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0] ?? '';
}

export async function persistAnalyzedOpportunities(context: WorkspaceContext, analyses: DomainAnalysis[], source: string): Promise<PersistedOpportunity[]> {
  assertWorkspaceWriter(context);

  const results: PersistedOpportunity[] = [];
  for (const analysis of analyses) {
    const domainName = normalizePersistedDomain(analysis.domain);
    const domain = await prisma.domain.upsert({
      where: { workspaceId_name: { workspaceId: context.workspaceId, name: domainName } },
      update: {
        status: 'ACTIVE',
        source,
        metadata: { lastWorkflow: source, stale: analysis.stale } satisfies Prisma.JsonObject,
      },
      create: {
        workspaceId: context.workspaceId,
        createdById: context.userId,
        name: domainName,
        tld: getTld(domainName),
        source,
        metadata: { lastWorkflow: source, stale: analysis.stale } satisfies Prisma.JsonObject,
      },
      select: { id: true, name: true },
    });

    await prisma.domainCheck.create({
      data: {
        domainId: domain.id,
        available: analysis.available,
        registrationPrice: new Prisma.Decimal(analysis.registrationPrice),
        renewalPrice: new Prisma.Decimal(analysis.renewalPrice),
        premium: analysis.premium,
        registrar: analysis.registrar,
        status: analysis.stale ? 'STALE' : 'FRESH',
        checkedAt: new Date(analysis.checkedAt),
      },
    });

    await prisma.domainOpportunity.upsert({
      where: { domainId: domain.id },
      update: {
        score: analysis.score,
        riskLevel: analysis.riskLevel,
        estimatedRetailMin: new Prisma.Decimal(analysis.valuation.retailMin),
        estimatedRetailMax: new Prisma.Decimal(analysis.valuation.retailMax),
        buyerCount: analysis.buyerCount,
        status: 'ACTIVE',
        notes: `Generated by ${source}. Not legal or financial advice.`,
      },
      create: {
        workspaceId: context.workspaceId,
        domainId: domain.id,
        score: analysis.score,
        riskLevel: analysis.riskLevel,
        estimatedRetailMin: new Prisma.Decimal(analysis.valuation.retailMin),
        estimatedRetailMax: new Prisma.Decimal(analysis.valuation.retailMax),
        buyerCount: analysis.buyerCount,
        status: 'ACTIVE',
        notes: `Generated by ${source}. Not legal or financial advice.`,
      },
    });

    await prisma.domainScore.create({
      data: {
        domainId: domain.id,
        total: analysis.score,
        summary: `Explainable ${source} score for ${domainName}.`,
        factors: {
          create: analysis.factors.map((factor) => ({
            name: factor.name,
            value: factor.value,
            maxValue: factor.maxValue,
            explanation: factor.explanation,
          })),
        },
      },
    });

    await prisma.valuation.create({
      data: {
        domainId: domain.id,
        wholesale: new Prisma.Decimal(analysis.valuation.wholesale),
        retailMin: new Prisma.Decimal(analysis.valuation.retailMin),
        retailMax: new Prisma.Decimal(analysis.valuation.retailMax),
        buyNow: new Prisma.Decimal(analysis.valuation.buyNow),
        minOffer: new Prisma.Decimal(Math.round(analysis.valuation.retailMin * 0.65)),
        maxAcquisition: new Prisma.Decimal(analysis.valuation.maxAcquisition),
        confidence: analysis.valuation.confidence,
        explanation: 'Development valuation range generated from score, TLD, buyer count, and mock acquisition economics.',
      },
    });

    results.push({
      domainId: domain.id,
      name: domain.name,
      score: analysis.score,
      riskLevel: analysis.riskLevel,
      available: analysis.available,
    });
  }

  return results;
}

export async function generateAnalyzeAndPersist(context: WorkspaceContext, input: GenerationInput): Promise<PersistedOpportunity[]> {
  const parsed = generationSchema.parse(input);
  const domains = generateDomainIdeas(parsed);
  const analyses = await analyzeDomains(domains, parsed.industry);
  return persistAnalyzedOpportunities(context, analyses, 'GENERATOR');
}

export async function importAnalyzeAndPersist(context: WorkspaceContext, rawDomains: string, industry: string): Promise<PersistedOpportunity[]> {
  const domains = parseDomainLines(rawDomains);
  if (domains.length === 0) throw new Error('No valid domains were provided.');
  const analyses = await analyzeDomains(domains, industry || 'general');
  return persistAnalyzedOpportunities(context, analyses, 'MANUAL_OR_CSV_IMPORT');
}
