import Link from 'next/link';
import { notFound } from 'next/navigation';
import {
  addBuyerContact,
  logBuyerActivity,
  markContactDoNotContact,
  updateBuyer,
  updateBuyerContact,
} from '../actions';
import { getBuyerDetail } from '@/lib/server/buyer-research';

export const dynamic = 'force-dynamic';

export default async function BuyerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const buyer = await getBuyerDetail((await params).id); if (!buyer) notFound();
  return <div>
    <Link className="text-sm text-slate-400" href="/buyer-research">Back to buyer research</Link>
    <div className="mt-4"><h1 className="text-3xl font-bold">{buyer.companyName}</h1><p className="mt-2 text-sm text-slate-400">CRM detail for {buyer.domain.name}</p></div>
    <form action={updateBuyer} className="card mt-6 grid gap-3 md:grid-cols-2"><input name="id" type="hidden" value={buyer.id} /><h2 className="text-xl font-semibold md:col-span-2">Buyer profile</h2><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.companyName} name="companyName" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.website ?? ''} name="website" type="url" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.industry} name="industry" required /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.location ?? ''} name="location" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.relevanceScore} max="100" min="0" name="relevanceScore" type="number" /><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={buyer.outreachStatus} name="outreachStatus">{['RESEARCHING','READY','CONTACTED','RESPONDED','QUALIFIED','CLOSED'].map((status) => <option key={status}>{status}</option>)}</select><textarea className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 md:col-span-2" defaultValue={buyer.reasonForFit} name="reasonForFit" rows={2} /><textarea className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 md:col-span-2" defaultValue={buyer.notes ?? ''} name="notes" placeholder="Notes" rows={3} /><button className="rounded-lg bg-brand px-4 py-2 font-semibold md:col-span-2">Save profile</button></form>
    <section className="mt-6"><h2 className="text-xl font-semibold">Contacts</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{buyer.contacts.map((contact) => <div className="card" key={contact.id}><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{contact.name ?? contact.email ?? 'Contact'}</h3>{contact.doNotContact ? <span className="text-xs font-semibold text-rose-300">DO NOT CONTACT</span> : null}</div><form action={updateBuyerContact} className="mt-3 grid gap-2 sm:grid-cols-2"><input name="buyerId" type="hidden" value={buyer.id} /><input name="contactId" type="hidden" value={contact.id} /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={contact.name ?? ''} name="name" placeholder="Name" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={contact.title ?? ''} name="title" placeholder="Title" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={contact.email ?? ''} name="email" placeholder="Email" type="email" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={contact.phone ?? ''} name="phone" placeholder="Phone" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 sm:col-span-2" defaultValue={contact.linkedinUrl ?? ''} name="linkedinUrl" placeholder="LinkedIn URL" type="url" /><textarea className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 sm:col-span-2" defaultValue={contact.notes ?? ''} name="notes" placeholder="Notes" rows={2} /><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" defaultValue={contact.status} name="status"><option>ACTIVE</option><option>INACTIVE</option></select><button className="rounded-lg bg-brand px-3 py-2 text-sm font-semibold">Save contact</button></form>{!contact.doNotContact && contact.email ? <form action={markContactDoNotContact} className="mt-3 flex gap-2"><input name="buyerId" type="hidden" value={buyer.id} /><input name="contactId" type="hidden" value={contact.id} /><input className="min-w-0 flex-1 rounded-lg border border-white/10 bg-slate-950 px-2 py-1 text-sm" name="reason" placeholder="Suppression reason" required /><button className="text-xs font-semibold text-rose-300">Suppress</button></form> : null}</div>)}</div>
      <form action={addBuyerContact} className="card mt-4 grid gap-3 md:grid-cols-3"><input name="buyerId" type="hidden" value={buyer.id} /><h3 className="font-semibold md:col-span-3">Add contact</h3><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="name" placeholder="Name" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="title" placeholder="Title" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="email" placeholder="Email" type="email" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="phone" placeholder="Phone" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="linkedinUrl" placeholder="LinkedIn URL" type="url" /><input className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="notes" placeholder="Notes" /><button className="rounded-lg bg-brand px-4 py-2 font-semibold md:col-span-3">Add contact</button></form>
    </section>
    <section className="mt-6 grid gap-4 lg:grid-cols-2"><form action={logBuyerActivity} className="card grid gap-3"><input name="buyerId" type="hidden" value={buyer.id} /><h2 className="text-xl font-semibold">Log activity</h2><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="contactId"><option value="">Buyer-level activity</option>{buyer.contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name ?? contact.email}</option>)}</select><select className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="type"><option>NOTE</option><option>CALL</option><option>MEETING</option><option>RESPONSE</option></select><textarea className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2" name="summary" placeholder="Activity summary" required rows={3} /><button className="rounded-lg bg-brand px-4 py-2 font-semibold">Add activity</button></form><div><h2 className="text-xl font-semibold">Activity history</h2><div className="mt-3 divide-y divide-white/10">{buyer.activities.length ? buyer.activities.map((activity) => <div className="py-3" key={activity.id}><p className="font-medium">{activity.type}</p><p className="mt-1 text-sm text-slate-300">{activity.summary}</p><p className="mt-1 text-xs text-slate-500">{activity.occurredAt.toLocaleString()}</p></div>) : <p className="text-sm text-slate-400">No activity recorded.</p>}</div></div></section>
  </div>;
}
